### PR TITLE
ComboBox is not populated async

### PR DESCRIPTION
**Pull request by Brains**
> @Brains can you provide a PR that adds the working sample to the sample project as a new tab?
Probably that's the important part that missing if you provide only some detached xaml: "... Data for DataGrid is loaded async from DB."

Reproduced
Sorry, but not in a new tab, was faster to do it in Extended 2

### CODE REVIEW

**Comment by Brains** [comment]
Looks so

**Comment by Brains** [comment]
Have no idea how, but `NotifyOnTargetUpdated=True` has fixed the issue

**Comment by Brains** [comment]
However, found a flaw in the previous fix: when doing traverse by date, that is a new `async` call to database each time a user presses a button, the filter randomly unchecks some items. Each button press causes a new assignment to `Events` property in view-model, binding to which looks so:
```xml
<DataGrid Name="EventsTable" 
          ItemsSource="{Binding Events, NotifyOnTargetUpdated=True}"
          IsReadOnly="True"
          AutoGenerateColumns="False"
          dgx:DataGridFilter.IsAutoFilterEnabled="True">
```
Each time I press on the arrow button at bottom only once, it is not very clear from `.gif`



I tried to clear the filter on `TargetUpdate` event in code-behind:
```cs
void EventsTable_OnTargetUpdated(object _, DataTransferEventArgs __)
{
    EventsTable.GetFilter().Clear();
}
```
It caused a noticeable delay `~400ms` where I see that initially the `filter` has all items selected but after the delay some items are randomly unselected:

**Comment by Brains** [comment]
Tried `ObservableCollection`, still no luck.
Before, I've reverted my past partial fix 5a144b2

In case, you wonder does `ObservableCollection` fix the issue in https://github.com/tom-englert/DataGridExtensions/pull/20#issuecomment-515097797 without reverting 5a144b2: I tried this in my project and no, does not fix.

Any ideas are appreciated.

**Comment by Brains** [comment]
Sorry, just noticed #27 issue which is quite similar. Rebasing this branch onto current `master`. 
However, without big hope because I updated my project to `2.2.0` before testing

**Comment by tom-englert** [comment]
Just replacing the list with the observable collection of course has no effect, you must use it like in 
2169fcf

**Comment by Brains** [comment]
Ok, sorry, used `Caliburn.Micro` for a long time, it does many things instead of me so I just forgot them. 

But even the correct usage of `ObservableCollection` had no effect. `ListBoxes` are still empty after `3` seconds delay:
image image

**Comment by Brains** [comment]
However, I have not `VS2019` currently so can't build your project under `Core 3`, just `cherry-picked` your last commit onto my old branch. So in case you fixed in 02e1e7076090229195fbf13119b869514bdde1b6 and everything works on `master` can you just check it (`ListBoxes` contain data after `3` seconds delay) and close the PR?

**Pull request closed without merging**
